using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Security.Cryptography;//***RNGCryptoServiceProvider***

class Program
{

    static byte[] GenerateKey(int messageLengthInBytes)
    {

        RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider();//Secure Random Generator

        byte[] key_generated = new byte[messageLengthInBytes];
        rng.GetBytes(key_generated);//Fills The key_generated Array With Randomly Generated Bytes

        return key_generated;

    }

    static byte[] XOR_ByteArrays(byte[] array1, byte[] array2)//Same Method Used For Encryption And Decryption
    {

        //Assumes Both Arrays Are Of The Same Length - Not Safe If Invalid Data Entered.

        byte[] array3 = new byte[array1.Length];//New Array To Hold Result Of XOR Operations

        for (int i = 0; i < array3.Length; i++)
        {

            int resultOfXOR = array1[i] ^ array2[i];//Hat Symbol Denotes XOR - Result Of Operation Is Int Data Type.
            array3[i] = (byte)resultOfXOR;//Casting The Above To Byte Data Type

        }

        return array3;

    }


    static void Main(string[] args)
    {

        string chosenOption;

        do
        {

            Console.WriteLine("MENU: ");
            Console.WriteLine("1. Encrypt Message: ");
            Console.WriteLine("2. Decrypt Message: ");
            Console.WriteLine("3. Quit");
            Console.WriteLine("Enter Option: ");
            chosenOption = Console.ReadLine();

            switch (chosenOption)
            {

                case "1":
                    Console.Write("Enter Message To Encrypt (ASCII): ");
                    string message = Console.ReadLine();//Data-Entry Purposes Only
                    byte[] message_byte_array = ASCIIEncoding.ASCII.GetBytes(message);

                    byte[] key = GenerateKey(message_byte_array.Length);
                    Console.WriteLine("Generated Key (Base64): " + Convert.ToBase64String(key));//Display Purposes Only.

                    byte[] ciphertext = XOR_ByteArrays(key, message_byte_array);
                    Console.WriteLine("Ciphertext (Base64): " + Convert.ToBase64String(ciphertext));//Display Purposes Only.
                    break;

                case "2":
                    Console.Write("Enter Message To Decrypt (Base64): ");
                    string ciphertext_string = Console.ReadLine();//Data-Entry Purposes Only
                    ciphertext = Convert.FromBase64String(ciphertext_string);

                    Console.Write("Enter Decryption Key (Base64): ");
                    string key_string = Console.ReadLine();//Data-Entry Purposes Only
                    key = Convert.FromBase64String(key_string);

                    message_byte_array = XOR_ByteArrays(key, ciphertext);
                    Console.WriteLine("Message (ASCII): " + ASCIIEncoding.ASCII.GetString(message_byte_array, 0, message_byte_array.Length));//Display Purposes Only.
                    break;

                case "3": break;
                default:
                    Console.WriteLine("Inavlid Option Chosen.");
                    break;

            }


        } while (chosenOption != "3");

    }
}